[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "zumm5hA1DC6dVo38XrQsuRiq5VN5guKrRh2dytidYCW"

[programs.devnet]
solana_twitter = "77kwy5AXqcMfqYqtZD5HkeENQznei2dAvEcuxxZxDXPS"

[programs.mainnet]
solana_twitter = "zumm5hA1DC6dVo38XrQsuRiq5VN5guKrRh2dytidYCW"

[registry]
url = "https://api.apr.dev"
#url = "http://localhost:8899"

[provider]
cluster = "devnet"
#cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"

[workspace]
types = "app/src/idl/"